x_0_MOTORS_CALIBRATE_VALUE_16 = 0
x_1_MOTORS_CALIBRATE_VALUE_16 = 0
x_0_SERVOPRIVOD_CALIBRATE_VALUE_16 = 0
x_1_SERVOPRIVOD_CALIBRATE_VALUE_16 = 0
x_0_CAM_CALIBRATE_VALUE_16 = 0
x_1_CAM_CALIBRATE_VALUE_16 = 0
x_0_MAN_CALIBRATE_VALUE_16 = 0
x_1_MAN_CALIBRATE_VALUE_16 = 0
x_2_MAN_CALIBRATE_VALUE_16 = 0
x_3_MAN_CALIBRATE_VALUE_16 = 0
x_4_MAN_CALIBRATE_VALUE_16 = 0
x_5_MAN_CALIBRATE_VALUE_16 = 0
x_6_MAN_CALIBRATE_VALUE_16 = 0
x_7_MAN_CALIBRATE_VALUE_16 = 0


MOTOR_SPEED = 40
MOVE_FORWARD = "w"
MOVE_BACKWARD = "s"
TURN_TANK_LEFT = "a"
TURN_TANK_RIGHT = "d"
TURN_LEFT = "q"
TURN_TIGHT = "e"

CAM_UP = "1"
CAM_DOWN = "2"

MAN_1_UP = "u"
MAN_1_DOWN = "h"
MAN2_UP = "i"
MAN2_DOWN = "j"
MAN3_UP = "o"
MAN3_DOWN = "k"
MAN4_UP = "p"
MAN4_DOWN = "l"
MOTOR_BOOST = "x"



